"""empty message

Revision ID: 8228c60463da
Revises: 
Create Date: 2018-05-22 19:29:22.597300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8228c60463da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alluser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.Column('IDcard', sa.String(length=64), nullable=True),
    sa.Column('pic', sa.String(length=128), nullable=True),
    sa.Column('license_num', sa.String(length=64), nullable=True),
    sa.Column('license_type', sa.String(length=64), nullable=True),
    sa.Column('scord', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('curlat', sa.Float(), nullable=True),
    sa.Column('curlng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alluser_username'), 'alluser', ['username'], unique=True)
    op.create_table('onliners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ipadd', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['alluser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onliners')
    op.drop_index(op.f('ix_alluser_username'), table_name='alluser')
    op.drop_table('alluser')
    # ### end Alembic commands ###
